// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgxncrtmkkvverrvwuzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1neG5jcnRta2t2dmVycnZ3dXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMjcyNTIsImV4cCI6MjA1NjgwMzI1Mn0.boBkdj-IFz3VIrEfPsK_uGuKmF71_BVhy8T4Uy2Iz_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);